# Generated by Django 3.2 on 2021-09-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager_api', '0002_bookableservice_entityservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityservice',
            name='payment_required',
            field=models.BooleanField(default=False),
        ),
    ]
