# Generated by Django 3.2 on 2021-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager_api', '0003_entityservice_payment_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityservice',
            name='sharing_consent_required',
            field=models.BooleanField(default=False),
        ),
    ]
