# Generated by Django 3.2 on 2021-09-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intel_api', '0007_alter_accesstoken_token'),
        ('booking_manager_api', '0005_alter_entityworkingdays_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitybookingschedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_booking_sched_creator', to='intel_api.userentity'),
        ),
    ]
