# Generated by Django 3.2 on 2021-11-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager_api', '0006_alter_entitybookingschedule_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityservice',
            name='service_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
