# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab_test_proto/lab_test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lab_test_proto/lab_test.proto',
  package='lab_test_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dlab_test_proto/lab_test.proto\x12\x0elab_test_proto\"v\n\x07LabTest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nlonic_code\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0f\n\x07\x64isease\x18\x04 \x01(\x05\x12\x0e\n\x06method\x18\x05 \x01(\t\x12\x0e\n\x06target\x18\x06 \x01(\t\x12\n\n\x02id\x18\x07 \x01(\x05\"\x14\n\x12LabTestListRequest\"$\n\x16LabTestRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xab\x01\n\x11LabTestController\x12G\n\x04List\x12\".lab_test_proto.LabTestListRequest\x1a\x17.lab_test_proto.LabTest\"\x00\x30\x01\x12M\n\x08Retrieve\x12&.lab_test_proto.LabTestRetrieveRequest\x1a\x17.lab_test_proto.LabTest\"\x00\x62\x06proto3'
)




_LABTEST = _descriptor.Descriptor(
  name='LabTest',
  full_name='lab_test_proto.LabTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='lab_test_proto.LabTest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lonic_code', full_name='lab_test_proto.LabTest.lonic_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='lab_test_proto.LabTest.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disease', full_name='lab_test_proto.LabTest.disease', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method', full_name='lab_test_proto.LabTest.method', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target', full_name='lab_test_proto.LabTest.target', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='lab_test_proto.LabTest.id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=167,
)


_LABTESTLISTREQUEST = _descriptor.Descriptor(
  name='LabTestListRequest',
  full_name='lab_test_proto.LabTestListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=189,
)


_LABTESTRETRIEVEREQUEST = _descriptor.Descriptor(
  name='LabTestRetrieveRequest',
  full_name='lab_test_proto.LabTestRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lab_test_proto.LabTestRetrieveRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=227,
)

DESCRIPTOR.message_types_by_name['LabTest'] = _LABTEST
DESCRIPTOR.message_types_by_name['LabTestListRequest'] = _LABTESTLISTREQUEST
DESCRIPTOR.message_types_by_name['LabTestRetrieveRequest'] = _LABTESTRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LabTest = _reflection.GeneratedProtocolMessageType('LabTest', (_message.Message,), {
  'DESCRIPTOR' : _LABTEST,
  '__module__' : 'lab_test_proto.lab_test_pb2'
  # @@protoc_insertion_point(class_scope:lab_test_proto.LabTest)
  })
_sym_db.RegisterMessage(LabTest)

LabTestListRequest = _reflection.GeneratedProtocolMessageType('LabTestListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LABTESTLISTREQUEST,
  '__module__' : 'lab_test_proto.lab_test_pb2'
  # @@protoc_insertion_point(class_scope:lab_test_proto.LabTestListRequest)
  })
_sym_db.RegisterMessage(LabTestListRequest)

LabTestRetrieveRequest = _reflection.GeneratedProtocolMessageType('LabTestRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _LABTESTRETRIEVEREQUEST,
  '__module__' : 'lab_test_proto.lab_test_pb2'
  # @@protoc_insertion_point(class_scope:lab_test_proto.LabTestRetrieveRequest)
  })
_sym_db.RegisterMessage(LabTestRetrieveRequest)



_LABTESTCONTROLLER = _descriptor.ServiceDescriptor(
  name='LabTestController',
  full_name='lab_test_proto.LabTestController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=230,
  serialized_end=401,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='lab_test_proto.LabTestController.List',
    index=0,
    containing_service=None,
    input_type=_LABTESTLISTREQUEST,
    output_type=_LABTEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='lab_test_proto.LabTestController.Retrieve',
    index=1,
    containing_service=None,
    input_type=_LABTESTRETRIEVEREQUEST,
    output_type=_LABTEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LABTESTCONTROLLER)

DESCRIPTOR.services_by_name['LabTestController'] = _LABTESTCONTROLLER

# @@protoc_insertion_point(module_scope)
