# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import lab_test_pb2 as lab__test__proto_dot_lab__test__pb2


class LabTestControllerStub(object):
    """import "google/protobuf/empty.proto";

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/lab_test_proto.LabTestController/List',
                request_serializer=lab__test__proto_dot_lab__test__pb2.LabTestListRequest.SerializeToString,
                response_deserializer=lab__test__proto_dot_lab__test__pb2.LabTest.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/lab_test_proto.LabTestController/Retrieve',
                request_serializer=lab__test__proto_dot_lab__test__pb2.LabTestRetrieveRequest.SerializeToString,
                response_deserializer=lab__test__proto_dot_lab__test__pb2.LabTest.FromString,
                )


class LabTestControllerServicer(object):
    """import "google/protobuf/empty.proto";

    """

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """rpc Create(LabTest) returns (LabTest) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LabTestControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=lab__test__proto_dot_lab__test__pb2.LabTestListRequest.FromString,
                    response_serializer=lab__test__proto_dot_lab__test__pb2.LabTest.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=lab__test__proto_dot_lab__test__pb2.LabTestRetrieveRequest.FromString,
                    response_serializer=lab__test__proto_dot_lab__test__pb2.LabTest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lab_test_proto.LabTestController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LabTestController(object):
    """import "google/protobuf/empty.proto";

    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/lab_test_proto.LabTestController/List',
            lab__test__proto_dot_lab__test__pb2.LabTestListRequest.SerializeToString,
            lab__test__proto_dot_lab__test__pb2.LabTest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lab_test_proto.LabTestController/Retrieve',
            lab__test__proto_dot_lab__test__pb2.LabTestRetrieveRequest.SerializeToString,
            lab__test__proto_dot_lab__test__pb2.LabTest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
