# Generated by Django 3.2 on 2021-09-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intel_api', '0002_userentity'),
        ('clients_booking_api', '0002_alter_userbookservice_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookservice',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intel_api.userentity'),
        ),
    ]
