# Generated by Django 3.2 on 2021-10-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_booking_api', '0003_alter_userbookservice_booked_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userbookservice',
            constraint=models.UniqueConstraint(fields=('code',), name='unique code'),
        ),
    ]
