# Generated by Django 3.2 on 2021-11-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients_booking_api', '0004_userbookservice_unique code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookTravelInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_date', models.DateTimeField(null=True)),
                ('departure_country', models.CharField(max_length=100, null=True)),
                ('arrival_country', models.CharField(max_length=100, null=True)),
                ('passport_number', models.CharField(max_length=100, null=True)),
                ('transport_operator', models.CharField(max_length=100, null=True)),
                ('userbookservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients_booking_api.userbookservice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userbooktravelinformation',
            constraint=models.UniqueConstraint(fields=('userbookservice',), name='unique booking'),
        ),
    ]
