# Generated by Django 3.2 on 2021-09-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_id', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
