# Generated by Django 3.2 on 2021-09-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intel_api', '0002_userentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=200)),
                ('token', models.CharField(default='b481e21750ee7af7a2786cd235ab47fa8c331fe9', max_length=200)),
                ('is_login', models.BooleanField(default=True)),
                ('user_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intel_api.userentity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
