# Generated by Django 3.2 on 2021-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_api', '0003_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(default='dee9aa97ddf9b28edcce1f32739be80d8be43cea', max_length=200),
        ),
        migrations.AlterField(
            model_name='externalentity',
            name='entity_type',
            field=models.CharField(choices=[('Lab', 'Lab')], max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='externalentity',
            constraint=models.UniqueConstraint(fields=('entity_id', 'entity_type'), name='unique entity'),
        ),
    ]
