# Generated by Django 3.2 on 2021-09-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_api', '0004_auto_20210925_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(default='4ff4a2c242aeee768d9d09c5bd34a3be88654d5d', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='userentity',
            constraint=models.UniqueConstraint(fields=('user_profile_id', 'username'), name='unique user entity'),
        ),
    ]
