# Generated by Django 3.2 on 2021-09-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_api', '0005_auto_20210925_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(default='44b2a9458177bfd77132600234a41a8223df0274', max_length=200),
        ),
    ]
