# Generated by Django 3.2 on 2021-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_api', '0006_alter_accesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(default='f3916184ce6004393ffd8b6e30fed8decfb13507', max_length=200),
        ),
    ]
