# Generated by Django 3.2 on 2021-10-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_api', '0007_alter_accesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(default='daaa9896f7ea1776f893aeab556ce7e7bf4cf45e', max_length=200),
        ),
    ]
