# Generated by Django 3.2 on 2021-10-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_api', '0008_alter_accesstoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
