# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signup/signup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signup/signup.proto',
  package='signup',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13signup/signup.proto\x12\x06signup\"\x9a\x01\n\x11UserSignupRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\x12\x11\n\tdial_code\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\x12\x14\n\x0credirect_url\x18\x07 \x01(\t\"J\n\x0cUserAuthUUID\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\"A\n\x0cVerification\x12\x10\n\x08verified\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1b\n\x0bUUIDRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"/\n\x0cUUIDResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xdf\x01\n\x14UserSignupController\x12?\n\nUserSignup\x12\x19.signup.UserSignupRequest\x1a\x14.signup.UserAuthUUID\"\x00\x12?\n\x0fOTPVerification\x12\x14.signup.UserAuthUUID\x1a\x14.signup.Verification\"\x00\x12\x45\n\x16ResendVerificationCode\x12\x13.signup.UUIDRequest\x1a\x14.signup.UUIDResponse\"\x00\x62\x06proto3'
)




_USERSIGNUPREQUEST = _descriptor.Descriptor(
  name='UserSignupRequest',
  full_name='signup.UserSignupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='signup.UserSignupRequest.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='signup.UserSignupRequest.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='signup.UserSignupRequest.phone_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dial_code', full_name='signup.UserSignupRequest.dial_code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='signup.UserSignupRequest.email', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='signup.UserSignupRequest.password', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='redirect_url', full_name='signup.UserSignupRequest.redirect_url', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=186,
)


_USERAUTHUUID = _descriptor.Descriptor(
  name='UserAuthUUID',
  full_name='signup.UserAuthUUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='signup.UserAuthUUID.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='otp', full_name='signup.UserAuthUUID.otp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='signup.UserAuthUUID.status', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='signup.UserAuthUUID.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=262,
)


_VERIFICATION = _descriptor.Descriptor(
  name='Verification',
  full_name='signup.Verification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='verified', full_name='signup.Verification.verified', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='signup.Verification.status', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='signup.Verification.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=329,
)


_UUIDREQUEST = _descriptor.Descriptor(
  name='UUIDRequest',
  full_name='signup.UUIDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='signup.UUIDRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=358,
)


_UUIDRESPONSE = _descriptor.Descriptor(
  name='UUIDResponse',
  full_name='signup.UUIDResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='signup.UUIDResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='signup.UUIDResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=407,
)

DESCRIPTOR.message_types_by_name['UserSignupRequest'] = _USERSIGNUPREQUEST
DESCRIPTOR.message_types_by_name['UserAuthUUID'] = _USERAUTHUUID
DESCRIPTOR.message_types_by_name['Verification'] = _VERIFICATION
DESCRIPTOR.message_types_by_name['UUIDRequest'] = _UUIDREQUEST
DESCRIPTOR.message_types_by_name['UUIDResponse'] = _UUIDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserSignupRequest = _reflection.GeneratedProtocolMessageType('UserSignupRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERSIGNUPREQUEST,
  '__module__' : 'signup.signup_pb2'
  # @@protoc_insertion_point(class_scope:signup.UserSignupRequest)
  })
_sym_db.RegisterMessage(UserSignupRequest)

UserAuthUUID = _reflection.GeneratedProtocolMessageType('UserAuthUUID', (_message.Message,), {
  'DESCRIPTOR' : _USERAUTHUUID,
  '__module__' : 'signup.signup_pb2'
  # @@protoc_insertion_point(class_scope:signup.UserAuthUUID)
  })
_sym_db.RegisterMessage(UserAuthUUID)

Verification = _reflection.GeneratedProtocolMessageType('Verification', (_message.Message,), {
  'DESCRIPTOR' : _VERIFICATION,
  '__module__' : 'signup.signup_pb2'
  # @@protoc_insertion_point(class_scope:signup.Verification)
  })
_sym_db.RegisterMessage(Verification)

UUIDRequest = _reflection.GeneratedProtocolMessageType('UUIDRequest', (_message.Message,), {
  'DESCRIPTOR' : _UUIDREQUEST,
  '__module__' : 'signup.signup_pb2'
  # @@protoc_insertion_point(class_scope:signup.UUIDRequest)
  })
_sym_db.RegisterMessage(UUIDRequest)

UUIDResponse = _reflection.GeneratedProtocolMessageType('UUIDResponse', (_message.Message,), {
  'DESCRIPTOR' : _UUIDRESPONSE,
  '__module__' : 'signup.signup_pb2'
  # @@protoc_insertion_point(class_scope:signup.UUIDResponse)
  })
_sym_db.RegisterMessage(UUIDResponse)



_USERSIGNUPCONTROLLER = _descriptor.ServiceDescriptor(
  name='UserSignupController',
  full_name='signup.UserSignupController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=410,
  serialized_end=633,
  methods=[
  _descriptor.MethodDescriptor(
    name='UserSignup',
    full_name='signup.UserSignupController.UserSignup',
    index=0,
    containing_service=None,
    input_type=_USERSIGNUPREQUEST,
    output_type=_USERAUTHUUID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='OTPVerification',
    full_name='signup.UserSignupController.OTPVerification',
    index=1,
    containing_service=None,
    input_type=_USERAUTHUUID,
    output_type=_VERIFICATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ResendVerificationCode',
    full_name='signup.UserSignupController.ResendVerificationCode',
    index=2,
    containing_service=None,
    input_type=_UUIDREQUEST,
    output_type=_UUIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSIGNUPCONTROLLER)

DESCRIPTOR.services_by_name['UserSignupController'] = _USERSIGNUPCONTROLLER

# @@protoc_insertion_point(module_scope)
