# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import signup_pb2 as signup_dot_signup__pb2


class UserSignupControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserSignup = channel.unary_unary(
                '/signup.UserSignupController/UserSignup',
                request_serializer=signup_dot_signup__pb2.UserSignupRequest.SerializeToString,
                response_deserializer=signup_dot_signup__pb2.UserAuthUUID.FromString,
                )
        self.OTPVerification = channel.unary_unary(
                '/signup.UserSignupController/OTPVerification',
                request_serializer=signup_dot_signup__pb2.UserAuthUUID.SerializeToString,
                response_deserializer=signup_dot_signup__pb2.Verification.FromString,
                )
        self.ResendVerificationCode = channel.unary_unary(
                '/signup.UserSignupController/ResendVerificationCode',
                request_serializer=signup_dot_signup__pb2.UUIDRequest.SerializeToString,
                response_deserializer=signup_dot_signup__pb2.UUIDResponse.FromString,
                )


class UserSignupControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserSignup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OTPVerification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResendVerificationCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserSignupControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserSignup': grpc.unary_unary_rpc_method_handler(
                    servicer.UserSignup,
                    request_deserializer=signup_dot_signup__pb2.UserSignupRequest.FromString,
                    response_serializer=signup_dot_signup__pb2.UserAuthUUID.SerializeToString,
            ),
            'OTPVerification': grpc.unary_unary_rpc_method_handler(
                    servicer.OTPVerification,
                    request_deserializer=signup_dot_signup__pb2.UserAuthUUID.FromString,
                    response_serializer=signup_dot_signup__pb2.Verification.SerializeToString,
            ),
            'ResendVerificationCode': grpc.unary_unary_rpc_method_handler(
                    servicer.ResendVerificationCode,
                    request_deserializer=signup_dot_signup__pb2.UUIDRequest.FromString,
                    response_serializer=signup_dot_signup__pb2.UUIDResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'signup.UserSignupController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserSignupController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserSignup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/signup.UserSignupController/UserSignup',
            signup_dot_signup__pb2.UserSignupRequest.SerializeToString,
            signup_dot_signup__pb2.UserAuthUUID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OTPVerification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/signup.UserSignupController/OTPVerification',
            signup_dot_signup__pb2.UserAuthUUID.SerializeToString,
            signup_dot_signup__pb2.Verification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResendVerificationCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/signup.UserSignupController/ResendVerificationCode',
            signup_dot_signup__pb2.UUIDRequest.SerializeToString,
            signup_dot_signup__pb2.UUIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
