# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userbookservice/user_book_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='userbookservice/user_book_service.proto',
  package='userbookservice',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'userbookservice/user_book_service.proto\x12\x0fuserbookservice\"*\n\x1aUserBookServiceCodeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\xa4\x01\n\x0fUserBookService\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tbooked_by\x18\x02 \x01(\t\x12\x1d\n\x15\x62ooked_entity_service\x18\x03 \x01(\t\x12\x15\n\rschedule_date\x18\x04 \x01(\t\x12\x1f\n\x17\x65ntity_booking_schedule\x18\x05 \x01(\t\x12\x0c\n\x04\x63ode\x18\x06 \x01(\t\x12\r\n\x05payed\x18\x07 \x01(\x08\x32\x86\x01\n\x19UserBookServiceController\x12i\n\x16GetBookedServiceByCode\x12+.userbookservice.UserBookServiceCodeRequest\x1a .userbookservice.UserBookService\"\x00\x62\x06proto3'
)




_USERBOOKSERVICECODEREQUEST = _descriptor.Descriptor(
  name='UserBookServiceCodeRequest',
  full_name='userbookservice.UserBookServiceCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='userbookservice.UserBookServiceCodeRequest.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=102,
)


_USERBOOKSERVICE = _descriptor.Descriptor(
  name='UserBookService',
  full_name='userbookservice.UserBookService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='userbookservice.UserBookService.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='booked_by', full_name='userbookservice.UserBookService.booked_by', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='booked_entity_service', full_name='userbookservice.UserBookService.booked_entity_service', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schedule_date', full_name='userbookservice.UserBookService.schedule_date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_booking_schedule', full_name='userbookservice.UserBookService.entity_booking_schedule', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='userbookservice.UserBookService.code', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payed', full_name='userbookservice.UserBookService.payed', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=269,
)

DESCRIPTOR.message_types_by_name['UserBookServiceCodeRequest'] = _USERBOOKSERVICECODEREQUEST
DESCRIPTOR.message_types_by_name['UserBookService'] = _USERBOOKSERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserBookServiceCodeRequest = _reflection.GeneratedProtocolMessageType('UserBookServiceCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERBOOKSERVICECODEREQUEST,
  '__module__' : 'userbookservice.user_book_service_pb2'
  # @@protoc_insertion_point(class_scope:userbookservice.UserBookServiceCodeRequest)
  })
_sym_db.RegisterMessage(UserBookServiceCodeRequest)

UserBookService = _reflection.GeneratedProtocolMessageType('UserBookService', (_message.Message,), {
  'DESCRIPTOR' : _USERBOOKSERVICE,
  '__module__' : 'userbookservice.user_book_service_pb2'
  # @@protoc_insertion_point(class_scope:userbookservice.UserBookService)
  })
_sym_db.RegisterMessage(UserBookService)



_USERBOOKSERVICECONTROLLER = _descriptor.ServiceDescriptor(
  name='UserBookServiceController',
  full_name='userbookservice.UserBookServiceController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=272,
  serialized_end=406,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBookedServiceByCode',
    full_name='userbookservice.UserBookServiceController.GetBookedServiceByCode',
    index=0,
    containing_service=None,
    input_type=_USERBOOKSERVICECODEREQUEST,
    output_type=_USERBOOKSERVICE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERBOOKSERVICECONTROLLER)

DESCRIPTOR.services_by_name['UserBookServiceController'] = _USERBOOKSERVICECONTROLLER

# @@protoc_insertion_point(module_scope)
