# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import user_book_service_pb2 as userbookservice_dot_user__book__service__pb2


class UserBookServiceControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookedServiceByCode = channel.unary_unary(
                '/userbookservice.UserBookServiceController/GetBookedServiceByCode',
                request_serializer=userbookservice_dot_user__book__service__pb2.UserBookServiceCodeRequest.SerializeToString,
                response_deserializer=userbookservice_dot_user__book__service__pb2.UserBookService.FromString,
                )


class UserBookServiceControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookedServiceByCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserBookServiceControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookedServiceByCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookedServiceByCode,
                    request_deserializer=userbookservice_dot_user__book__service__pb2.UserBookServiceCodeRequest.FromString,
                    response_serializer=userbookservice_dot_user__book__service__pb2.UserBookService.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'userbookservice.UserBookServiceController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserBookServiceController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookedServiceByCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/userbookservice.UserBookServiceController/GetBookedServiceByCode',
            userbookservice_dot_user__book__service__pb2.UserBookServiceCodeRequest.SerializeToString,
            userbookservice_dot_user__book__service__pb2.UserBookService.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
